name: cs273

channels:
  - conda-forge

dependencies:
  - black
  - flake8
  - python=3.10
  - ipdb
  - ipython
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytorch
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - wandb
  - pip:
    - gdown
